#!/bin/bash

# Disable mouse and power management
unclutter -idle 0.1 -root &
xset dpms 0 0 0
xset -dpms      # Disable power management
xset s off      # Disable screen saver
xset s noblank  # Prevent screen blanking

# Put up a message
xmessage -center -buttons "" "Waiting for frame to connect to Roon..." &
XMESSAGE_PID=$!

# Wait for the frame server to be available
URL="http://127.0.0.1:5006"
echo "Waiting for $URL to be available..."
while true; do
    STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
    
    if [ "$STATUS_CODE" -eq 200 ]; then
        echo "$URL is up!"
        kill $XMESSAGE_PID 
        break
    fi

    echo "Still waiting..."
    sleep 1
done

# Start Chromium in kiosk mode
exec chromium-browser --window-size=1024,600 --enable-logging=stderr --v1 --noerrdialogs --disable-infobars --hide-scrollbars --kiosk "$URL"
